---
# Environnement dev
- name: Deploy Todos API stack (dev)
  hosts: devops_dev
  become: true
  roles:
    - role: database
    - role: runtime
    - role: app
    - role: webserver
    - role: maildev
    - role: postfix
    - role: backup
    - role: certbot

# Environnement staging
- name: Deploy Todos API stack (staging)
  hosts: devops_staging
  become: true
  roles:
    - role: database
    - role: runtime
    - role: app
    - role: webserver
    - role: maildev
    - role: postfix
    - role: backup
    - role: certbot
